Upgrade to new namespace convention. Add py 3.11 and py3.12
openalea/lpy pull request #43
Opened 2024-01-25 10:01 UTC by fredboudon

2024-01-25 18:44 UTC, pradal requested changes
Just update the setup.py

2024-01-25 18:44 UTC, pradal commented on setup.py
It seems that the namespace has not been managed

2024-01-25 18:44 UTC, pradal commented on setup.py
namespace_packages = [namespace],
        create_namespaces = False,

has to be removed line 71

2024-01-25 18:44 UTC, pradal commented on setup.py
and namespace has to be removed line 87

2024-01-26 16:50 UTC, pradal commented
@fredboudon : we need PyQGLViewer in openalea3 channel...

> pyqglviewer >=1.3

2024-01-28 14:29 UTC, merged

2024-01-29 12:05 UTC, fredboudon commented
You can use the one that is built on my channel. I'm not sure to know how to copy these packages

2024-01-29 12:23 UTC, pradal commented
I have make a fork on OpenAlea to have it in the OpenAlea channel also.
Then the openalea3 channel is self-consistent.
Thanks again.